/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * Unauthorized
 */
export type GetDestinationsDestinationsResponseBodyData = {
    /**
     * Message of the error
     */
    message?: string | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Unauthorized
 */
export class GetDestinationsDestinationsResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetDestinationsDestinationsResponseBodyData;

    constructor(err: GetDestinationsDestinationsResponseBodyData, options?: ErrorOptions) {
        super("", options);
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "GetDestinationsDestinationsResponseBody";
    }
}

/**
 * Bad Request
 */
export type GetDestinationsResponseBodyData = {
    /**
     * Message of the error
     */
    message?: string | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Bad Request
 */
export class GetDestinationsResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetDestinationsResponseBodyData;

    constructor(err: GetDestinationsResponseBodyData, options?: ErrorOptions) {
        super("", options);
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "GetDestinationsResponseBody";
    }
}

/** @internal */
export namespace GetDestinationsDestinationsResponseBody$ {
    export type Inbound = {
        message?: string | undefined;
        RawResponse?: Response | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetDestinationsDestinationsResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            message: z.string().optional(),
            RawResponse: z.instanceof(Response).optional(),
        })
        .transform((v) => {
            return new GetDestinationsDestinationsResponseBody({
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
            });
        });
    export type Outbound = {
        message?: string | undefined;
        RawResponse?: never | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetDestinationsDestinationsResponseBody
    > = z
        .instanceof(GetDestinationsDestinationsResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    message: z.string().optional(),
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.message === undefined ? null : { message: v.message }),
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                    };
                })
        );
}

/** @internal */
export namespace GetDestinationsResponseBody$ {
    export type Inbound = {
        message?: string | undefined;
        RawResponse?: Response | undefined;
    };

    export const inboundSchema: z.ZodType<GetDestinationsResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            message: z.string().optional(),
            RawResponse: z.instanceof(Response).optional(),
        })
        .transform((v) => {
            return new GetDestinationsResponseBody({
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
            });
        });
    export type Outbound = {
        message?: string | undefined;
        RawResponse?: never | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDestinationsResponseBody> = z
        .instanceof(GetDestinationsResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    message: z.string().optional(),
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.message === undefined ? null : { message: v.message }),
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                    };
                })
        );
}
