/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * Unauthorized
 */
export type GetPurchaseConsumptionPurchasesResponseBodyData = {
    /**
     * Message of the error
     */
    message?: string | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Unauthorized
 */
export class GetPurchaseConsumptionPurchasesResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetPurchaseConsumptionPurchasesResponseBodyData;

    constructor(err: GetPurchaseConsumptionPurchasesResponseBodyData, options?: ErrorOptions) {
        super("", options);
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "GetPurchaseConsumptionPurchasesResponseBody";
    }
}

/**
 * Bad Request
 */
export type GetPurchaseConsumptionResponseBodyData = {
    /**
     * Message of the error
     */
    message?: string | undefined;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
};

/**
 * Bad Request
 */
export class GetPurchaseConsumptionResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetPurchaseConsumptionResponseBodyData;

    constructor(err: GetPurchaseConsumptionResponseBodyData, options?: ErrorOptions) {
        super("", options);
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "GetPurchaseConsumptionResponseBody";
    }
}

/** @internal */
export namespace GetPurchaseConsumptionPurchasesResponseBody$ {
    export type Inbound = {
        message?: string | undefined;
        RawResponse?: Response | undefined;
    };
    export type Outbound = {
        message?: string | undefined;
        rawResponse?: Response | undefined;
    };

    export const inboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Inbound> = z
        .object({
            message: z.string().optional(),
            RawResponse: z.instanceof(Response).optional(),
        })
        .transform((v) => {
            return {
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
            };
        });
}

/** @internal */
export namespace GetPurchaseConsumptionResponseBody$ {
    export type Inbound = {
        message?: string | undefined;
        RawResponse?: Response | undefined;
    };
    export type Outbound = {
        message?: string | undefined;
        rawResponse?: Response | undefined;
    };

    export const inboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Inbound> = z
        .object({
            message: z.string().optional(),
            RawResponse: z.instanceof(Response).optional(),
        })
        .transform((v) => {
            return {
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
            };
        });
}
