/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../models/errors";
import * as operations from "../models/operations";

export class Packages extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }
    /**
     * List Packages
     */
    async getPackages(
        input: operations.GetPackagesRequest,
        options?: RequestOptions
    ): Promise<operations.GetPackagesResponse> {
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Accept", "application/json");

        const payload = operations.GetPackagesRequest$.outboundSchema.parse(input);
        const body = null;

        const path = this.templateURLComponent("/packages")();

        const query = [
            enc$.encodeForm("afterCursor", payload.afterCursor, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("destination", payload.destination, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("duration", payload.duration, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("endDate", payload.endDate, { explode: true, charEncoding: "percent" }),
            enc$.encodeForm("endTime", payload.endTime, { explode: true, charEncoding: "percent" }),
            enc$.encodeForm("limit", payload.limit, { explode: true, charEncoding: "percent" }),
            enc$.encodeForm("startDate", payload.startDate, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("startTime", payload.startTime, {
                explode: true,
                charEncoding: "percent",
            }),
        ]
            .filter(Boolean)
            .join("&");

        const security = this.options$.oAuth2ClientCredentials
            ? { oAuth2ClientCredentials: this.options$.oAuth2ClientCredentials }
            : {};
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "get", path, headers, query, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.GetPackagesResponse$.inboundSchema.parse({
                ...responseFields,
                object: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, 400, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetPackagesResponseBody$.inboundSchema.parse({
                ...responseFields,
                ...responseBody,
            });
            throw new errors.GetPackagesResponseBody(result);
        } else if (this.matchResponse(response, 401, "application/json")) {
            const responseBody = await response.json();
            const result = errors.GetPackagesPackagesResponseBody$.inboundSchema.parse({
                ...responseFields,
                ...responseBody,
            });
            throw new errors.GetPackagesPackagesResponseBody(result);
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }
    }
}
