/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type GeteSIMMacRequest = {
    iccid: string;
};

export type GeteSIMMacEsim = {
    /**
     * ID of the eSIM
     */
    iccid?: string | undefined;
    /**
     * SM-DP+ Address
     */
    smdpAddress?: string | undefined;
    /**
     * The manual activation code
     */
    manualActivationCode?: string | undefined;
};

/**
 * Successful Response
 */
export type GeteSIMMacResponseBody = {
    esim?: GeteSIMMacEsim | undefined;
};

export type GeteSIMMacResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful Response
     */
    object?: GeteSIMMacResponseBody | undefined;
};

/** @internal */
export namespace GeteSIMMacRequest$ {
    export type Inbound = {
        iccid: string;
    };

    export const inboundSchema: z.ZodType<GeteSIMMacRequest, z.ZodTypeDef, Inbound> = z
        .object({
            iccid: z.string(),
        })
        .transform((v) => {
            return {
                iccid: v.iccid,
            };
        });

    export type Outbound = {
        iccid: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GeteSIMMacRequest> = z
        .object({
            iccid: z.string(),
        })
        .transform((v) => {
            return {
                iccid: v.iccid,
            };
        });
}

/** @internal */
export namespace GeteSIMMacEsim$ {
    export type Inbound = {
        iccid?: string | undefined;
        smdpAddress?: string | undefined;
        manualActivationCode?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GeteSIMMacEsim, z.ZodTypeDef, Inbound> = z
        .object({
            iccid: z.string().optional(),
            smdpAddress: z.string().optional(),
            manualActivationCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.iccid === undefined ? null : { iccid: v.iccid }),
                ...(v.smdpAddress === undefined ? null : { smdpAddress: v.smdpAddress }),
                ...(v.manualActivationCode === undefined
                    ? null
                    : { manualActivationCode: v.manualActivationCode }),
            };
        });

    export type Outbound = {
        iccid?: string | undefined;
        smdpAddress?: string | undefined;
        manualActivationCode?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GeteSIMMacEsim> = z
        .object({
            iccid: z.string().optional(),
            smdpAddress: z.string().optional(),
            manualActivationCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.iccid === undefined ? null : { iccid: v.iccid }),
                ...(v.smdpAddress === undefined ? null : { smdpAddress: v.smdpAddress }),
                ...(v.manualActivationCode === undefined
                    ? null
                    : { manualActivationCode: v.manualActivationCode }),
            };
        });
}

/** @internal */
export namespace GeteSIMMacResponseBody$ {
    export type Inbound = {
        esim?: GeteSIMMacEsim$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GeteSIMMacResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            esim: z.lazy(() => GeteSIMMacEsim$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.esim === undefined ? null : { esim: v.esim }),
            };
        });

    export type Outbound = {
        esim?: GeteSIMMacEsim$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GeteSIMMacResponseBody> = z
        .object({
            esim: z.lazy(() => GeteSIMMacEsim$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.esim === undefined ? null : { esim: v.esim }),
            };
        });
}

/** @internal */
export namespace GeteSIMMacResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: GeteSIMMacResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GeteSIMMacResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GeteSIMMacResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: GeteSIMMacResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GeteSIMMacResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GeteSIMMacResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
